[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    filetree_direction = "left"
    guifont = ""
    relativenumber = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
  name = "ui"
  enable_scrollbar = true

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#kotlin"

[[layers]]
    name = 'lang#c'
    enable_clang_syntax_highlight = true

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#python"

[[layers]]
    name = 'git'
[[layers]]
    name = 'VersionControl'

[[custom_plugins]]
    repo = "https://gitlab.com/code-stats/code-stats-vim.git"
    merged = false